# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hymyeLZZEPjKbHcsw2cjH5Vdc7IUsbTS
"""

!apt-get update -qq
!apt-get install -y sqlite3 libsqlite3-dev gcc

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sqlite3.h>

sqlite3 *db;

/* ---------- DATABASE ---------- */

void execute_sql(const char *sql)
{
    char *error = NULL;

    if (sqlite3_exec(db, sql, 0, 0, &error) != SQLITE_OK)
    {
        printf("Database Error: %s\n", error);
        sqlite3_free(error);
    }
}

void create_tables()
{
    execute_sql(
        "CREATE TABLE IF NOT EXISTS customers ("
        "customer_id INTEGER PRIMARY KEY AUTOINCREMENT,"
        "name TEXT NOT NULL,"
        "phone TEXT UNIQUE NOT NULL,"
        "email TEXT,"
        "address TEXT);");

    execute_sql(
        "CREATE TABLE IF NOT EXISTS cars ("
        "car_id INTEGER PRIMARY KEY AUTOINCREMENT,"
        "car_number TEXT UNIQUE NOT NULL,"
        "brand TEXT NOT NULL,"
        "model TEXT NOT NULL,"
        "car_type TEXT,"
        "rent_per_day REAL NOT NULL,"
        "status TEXT DEFAULT 'Available');");

    execute_sql(
        "CREATE TABLE IF NOT EXISTS rentals ("
        "rental_id INTEGER PRIMARY KEY AUTOINCREMENT,"
        "customer_id INTEGER,"
        "car_id INTEGER,"
        "rental_date TEXT,"
        "return_date TEXT,"
        "days INTEGER,"
        "total_amount REAL,"
        "status TEXT DEFAULT 'Rented',"
        "FOREIGN KEY(customer_id) REFERENCES customers(customer_id),"
        "FOREIGN KEY(car_id) REFERENCES cars(car_id));");

    execute_sql(
        "CREATE TABLE IF NOT EXISTS payments ("
        "payment_id INTEGER PRIMARY KEY AUTOINCREMENT,"
        "rental_id INTEGER,"
        "amount REAL,"
        "payment_date TEXT,"
        "payment_status TEXT DEFAULT 'Paid',"
        "FOREIGN KEY(rental_id) REFERENCES rentals(rental_id));");
}

/* ---------- SAMPLE CARS ---------- */

void insert_sample_cars()
{
    execute_sql(
        "INSERT OR IGNORE INTO cars "
        "(car_number, brand, model, car_type, rent_per_day) VALUES "
        "('TN01AB1234','Toyota','Innova','SUV',2500),"
        "('TN02CD5678','Hyundai','Creta','SUV',2200),"
        "('TN03EF9012','Maruti','Swift','Hatchback',1500),"
        "('TN04GH3456','Honda','City','Sedan',2000),"
        "('TN05IJ7890','Tata','Nexon','SUV',1800);");
}

/* ---------- VIEW CARS ---------- */

void view_cars()
{
    sqlite3_stmt *stmt;

    const char *sql =
        "SELECT car_id, car_number, brand, model, car_type, "
        "rent_per_day, status FROM cars;";

    if (sqlite3_prepare_v2(db, sql, -1, &stmt, NULL) != SQLITE_OK)
        return;

    printf("\n============================================================\n");
    printf("                    CAR LIST\n");
    printf("============================================================\n");

    printf("%-5s %-15s %-12s %-12s %-12s %-12s %-12s\n",
           "ID", "Number", "Brand", "Model", "Type",
           "Rent/Day", "Status");

    while (sqlite3_step(stmt) == SQLITE_ROW)
    {
        printf("%-5d %-15s %-12s %-12s %-12s ₹%-11.2f %-12s\n",
               sqlite3_column_int(stmt, 0),
               sqlite3_column_text(stmt, 1),
               sqlite3_column_text(stmt, 2),
               sqlite3_column_text(stmt, 3),
               sqlite3_column_text(stmt, 4),
               sqlite3_column_double(stmt, 5),
               sqlite3_column_text(stmt, 6));
    }

    sqlite3_finalize(stmt);
}

/* ---------- REGISTER CUSTOMER ---------- */

void register_customer()
{
    char name[100], phone[30], email[100], address[150];
    sqlite3_stmt *stmt;

    printf("\n========== CUSTOMER REGISTRATION ==========\n");

    printf("Enter Name    : ");
    scanf(" %[^\n]", name);

    printf("Enter Phone   : ");
    scanf(" %[^\n]", phone);

    printf("Enter Email   : ");
    scanf(" %[^\n]", email);

    printf("Enter Address : ");
    scanf(" %[^\n]", address);

    const char *sql =
        "INSERT INTO customers(name, phone, email, address) "
        "VALUES (?, ?, ?, ?);";

    sqlite3_prepare_v2(db, sql, -1, &stmt, NULL);

    sqlite3_bind_text(stmt, 1, name, -1, SQLITE_TRANSIENT);
    sqlite3_bind_text(stmt, 2, phone, -1, SQLITE_TRANSIENT);
    sqlite3_bind_text(stmt, 3, email, -1, SQLITE_TRANSIENT);
    sqlite3_bind_text(stmt, 4, address, -1, SQLITE_TRANSIENT);

    if (sqlite3_step(stmt) == SQLITE_DONE)
    {
        printf("\nCustomer registered successfully!\n");
        printf("Customer ID: %lld\n",
               sqlite3_last_insert_rowid(db));
    }
    else
    {
        printf("\nCustomer registration failed.\n");
    }

    sqlite3_finalize(stmt);
}

/* ---------- VIEW CUSTOMERS ---------- */

void view_customers()
{
    sqlite3_stmt *stmt;

    const char *sql =
        "SELECT customer_id, name, phone, email, address "
        "FROM customers;";

    sqlite3_prepare_v2(db, sql, -1, &stmt, NULL);

    printf("\n============================================================\n");
    printf("                  CUSTOMER LIST\n");
    printf("============================================================\n");

    printf("%-5s %-20s %-15s %-25s %-15s\n",
           "ID", "Name", "Phone", "Email", "Address");

    while (sqlite3_step(stmt) == SQLITE_ROW)
    {
        printf("%-5d %-20s %-15s %-25s %-15s\n",
               sqlite3_column_int(stmt, 0),
               sqlite3_column_text(stmt, 1),
               sqlite3_column_text(stmt, 2),
               sqlite3_column_text(stmt, 3),
               sqlite3_column_text(stmt, 4));
    }

    sqlite3_finalize(stmt);
}

/* ---------- RENT CAR ---------- */

void rent_car()
{
    int customer_id, car_id, days;
    double rent_per_day, total;
    sqlite3_stmt *stmt;

    printf("\n========== RENT CAR ==========\n");

    printf("Enter Customer ID : ");
    scanf("%d", &customer_id);

    printf("Enter Car ID      : ");
    scanf("%d", &car_id);

    printf("Enter Number of Days : ");
    scanf("%d", &days);

    if (days <= 0)
    {
        printf("Invalid number of days.\n");
        return;
    }

    const char *check_sql =
        "SELECT rent_per_day FROM cars "
        "WHERE car_id = ? AND status = 'Available';";

    sqlite3_prepare_v2(db, check_sql, -1, &stmt, NULL);
    sqlite3_bind_int(stmt, 1, car_id);

    if (sqlite3_step(stmt) != SQLITE_ROW)
    {
        printf("\nCar not available or invalid Car ID.\n");
        sqlite3_finalize(stmt);
        return;
    }

    rent_per_day = sqlite3_column_double(stmt, 0);
    sqlite3_finalize(stmt);

    total = rent_per_day * days;

    const char *insert_sql =
        "INSERT INTO rentals "
        "(customer_id, car_id, rental_date, days, total_amount, status) "
        "VALUES (?, ?, date('now'), ?, ?, 'Rented');";

    sqlite3_prepare_v2(db, insert_sql, -1, &stmt, NULL);

    sqlite3_bind_int(stmt, 1, customer_id);
    sqlite3_bind_int(stmt, 2, car_id);
    sqlite3_bind_int(stmt, 3, days);
    sqlite3_bind_double(stmt, 4, total);

    if (sqlite3_step(stmt) == SQLITE_DONE)
    {
        long long rental_id = sqlite3_last_insert_rowid(db);

        printf("\n====================================\n");
        printf("          CAR RENTED\n");
        printf("====================================\n");
        printf("Rental ID   : %lld\n", rental_id);
        printf("Total Amount: ₹%.2f\n", total);
        printf("Status      : Rented\n");
        printf("====================================\n");

        char update_sql[200];

        snprintf(update_sql, sizeof(update_sql),
                 "UPDATE cars SET status='Rented' "
                 "WHERE car_id=%d;", car_id);

        execute_sql(update_sql);
    }
    else
    {
        printf("\nRental failed.\n");
    }

    sqlite3_finalize(stmt);
}

/* ---------- RETURN CAR ---------- */

void return_car()
{
    int rental_id;
    sqlite3_stmt *stmt;

    printf("\n========== RETURN CAR ==========\n");

    printf("Enter Rental ID : ");
    scanf("%d", &rental_id);

    const char *sql =
        "SELECT car_id, total_amount "
        "FROM rentals "
        "WHERE rental_id = ? AND status = 'Rented';";

    sqlite3_prepare_v2(db, sql, -1, &stmt, NULL);
    sqlite3_bind_int(stmt, 1, rental_id);

    if (sqlite3_step(stmt) != SQLITE_ROW)
    {
        printf("\nRental not found or already returned.\n");
        sqlite3_finalize(stmt);
        return;
    }

    int car_id = sqlite3_column_int(stmt, 0);
    double amount = sqlite3_column_double(stmt, 1);

    sqlite3_finalize(stmt);

    char update_rental[300];

    snprintf(update_rental, sizeof(update_rental),
             "UPDATE rentals SET "
             "return_date=date('now'), status='Returned' "
             "WHERE rental_id=%d;",
             rental_id);

    execute_sql(update_rental);

    char update_car[200];

    snprintf(update_car, sizeof(update_car),
             "UPDATE cars SET status='Available' "
             "WHERE car_id=%d;",
             car_id);

    execute_sql(update_car);

    sqlite3_stmt *payment_stmt;

    const char *payment_sql =
        "INSERT INTO payments "
        "(rental_id, amount, payment_date, payment_status) "
        "VALUES (?, ?, date('now'), 'Paid');";

    sqlite3_prepare_v2(db, payment_sql, -1, &payment_stmt, NULL);

    sqlite3_bind_int(payment_stmt, 1, rental_id);
    sqlite3_bind_double(payment_stmt, 2, amount);

    sqlite3_step(payment_stmt);

    sqlite3_finalize(payment_stmt);

    printf("\n====================================\n");
    printf("          CAR RETURNED\n");
    printf("====================================\n");
    printf("Rental ID    : %d\n", rental_id);
    printf("Total Amount : ₹%.2f\n", amount);
    printf("Payment      : Paid\n");
    printf("Return Date  : Today\n");
    printf("====================================\n");
}

/* ---------- RENTAL HISTORY ---------- */

void rental_history()
{
    sqlite3_stmt *stmt;

    const char *sql =
        "SELECT r.rental_id, c.name, "
        "ca.brand, ca.model, "
        "r.rental_date, r.return_date, "
        "r.days, r.total_amount, r.status "
        "FROM rentals r "
        "JOIN customers c ON r.customer_id=c.customer_id "
        "JOIN cars ca ON r.car_id=ca.car_id;";

    sqlite3_prepare_v2(db, sql, -1, &stmt, NULL);

    printf("\n============================================================\n");
    printf("                    RENTAL HISTORY\n");
    printf("============================================================\n");

    while (sqlite3_step(stmt) == SQLITE_ROW)
    {
        printf("\nRental ID   : %d",
               sqlite3_column_int(stmt, 0));

        printf("\nCustomer    : %s",
               sqlite3_column_text(stmt, 1));

        printf("\nCar         : %s %s",
               sqlite3_column_text(stmt, 2),
               sqlite3_column_text(stmt, 3));

        printf("\nRental Date : %s",
               sqlite3_column_text(stmt, 4));

        printf("\nReturn Date : %s",
               sqlite3_column_text(stmt, 5)
                   ? (const char *)sqlite3_column_text(stmt, 5)
                   : "Not Returned");

        printf("\nDays        : %d",
               sqlite3_column_int(stmt, 6));

        printf("\nTotal       : ₹%.2f",
               sqlite3_column_double(stmt, 7));

        printf("\nStatus      : %s\n",
               sqlite3_column_text(stmt, 8));

        printf("--------------------------------------------\n");
    }

    sqlite3_finalize(stmt);
}

/* ---------- REVENUE REPORT ---------- */

void revenue_report()
{
    sqlite3_stmt *stmt;

    const char *sql =
        "SELECT "
        "COUNT(*), "
        "COALESCE(SUM(amount),0) "
        "FROM payments "
        "WHERE payment_status='Paid';";

    sqlite3_prepare_v2(db, sql, -1, &stmt, NULL);

    if (sqlite3_step(stmt) == SQLITE_ROW)
    {
        int payments = sqlite3_column_int(stmt, 0);
        double revenue = sqlite3_column_double(stmt, 1);

        printf("\n====================================\n");
        printf("          REVENUE REPORT\n");
        printf("====================================\n");
        printf("Total Payments : %d\n", payments);
        printf("Total Revenue  : ₹%.2f\n", revenue);
        printf("====================================\n");
    }

    sqlite3_finalize(stmt);
}

/* ---------- CUSTOMER MENU ---------- */

void customer_menu()
{
    int choice;

    do
    {
        printf("\n============================================\n");
        printf("              CUSTOMER MENU\n");
        printf("============================================\n");
        printf("1. Register Customer\n");
        printf("2. View Cars\n");
        printf("3. Rent Car\n");
        printf("4. Return Car\n");
        printf("5. Rental History\n");
        printf("6. Back\n");
        printf("============================================\n");

        printf("Enter Choice: ");
        scanf("%d", &choice);

        switch (choice)
        {
            case 1:
                register_customer();
                break;

            case 2:
                view_cars();
                break;

            case 3:
                rent_car();
                break;

            case 4:
                return_car();
                break;

            case 5:
                rental_history();
                break;

            case 6:
                break;

            default:
                printf("Invalid choice.\n");
        }

    } while (choice != 6);
}

/* ---------- ADMIN MENU ---------- */

void admin_menu()
{
    int choice;

    do
    {
        printf("\n============================================\n");
        printf("                ADMIN MENU\n");
        printf("============================================\n");
        printf("1. View Customers\n");
        printf("2. View Cars\n");
        printf("3. Rental History\n");
        printf("4. Revenue Report\n");
        printf("5. Back\n");
        printf("============================================\n");

        printf("Enter Choice: ");
        scanf("%d", &choice);

        switch (choice)
        {
            case 1:
                view_customers();
                break;

            case 2:
                view_cars();
                break;

            case 3:
                rental_history();
                break;

            case 4:
                revenue_report();
                break;

            case 5:
                break;

            default:
                printf("Invalid choice.\n");
        }

    } while (choice != 5);
}

/* ---------- MAIN ---------- */

int main()
{
    if (sqlite3_open("car_rental_system.db", &db) != SQLITE_OK)
    {
        printf("Database connection failed.\n");
        return 1;
    }

    execute_sql("PRAGMA foreign_keys = ON;");

    create_tables();
    insert_sample_cars();

    int choice;

    printf("\n");
    printf("============================================================\n");
    printf("              CAR RENTAL MANAGEMENT SYSTEM\n");
    printf("============================================================\n");

    do
    {
        printf("\n==================== MAIN MENU ====================\n");
        printf("1. Customer\n");
        printf("2. Admin\n");
        printf("3. Exit\n");
        printf("====================================================\n");

        printf("Enter Choice: ");
        scanf("%d", &choice);

        switch (choice)
        {
            case 1:
                customer_menu();
                break;

            case 2:
                admin_menu();
                break;

            case 3:
                printf("\nThank you for using Car Rental System!\n");
                break;

            default:
                printf("\nInvalid choice.\n");
        }

    } while (choice != 3);

    sqlite3_close(db);

    return 0;
}

# Commented out IPython magic to ensure Python compatibility.
# %%writefile car_rental.c
# #include <stdio.h>
# #include <stdlib.h>
# #include <string.h>
# #include <sqlite3.h>
# 
# sqlite3 *db;
# 
# /* ---------- DATABASE ---------- */
# 
# void execute_sql(const char *sql)
# {
#     char *error = NULL;
# 
#     if (sqlite3_exec(db, sql, 0, 0, &error) != SQLITE_OK)
#     {
#         printf("Database Error: %s\n", error);
#         sqlite3_free(error);
#     }
# }
# 
# void create_tables()
# {
#     execute_sql(
#         "CREATE TABLE IF NOT EXISTS customers ("
#         "customer_id INTEGER PRIMARY KEY AUTOINCREMENT,"
#         "name TEXT NOT NULL,"
#         "phone TEXT UNIQUE NOT NULL,"
#         "email TEXT,"
#         "address TEXT);");
# 
#     execute_sql(
#         "CREATE TABLE IF NOT EXISTS cars ("
#         "car_id INTEGER PRIMARY KEY AUTOINCREMENT,"
#         "car_number TEXT UNIQUE NOT NULL,"
#         "brand TEXT NOT NULL,"
#         "model TEXT NOT NULL,"
#         "car_type TEXT,"
#         "rent_per_day REAL NOT NULL,"
#         "status TEXT DEFAULT 'Available');");
# 
#     execute_sql(
#         "CREATE TABLE IF NOT EXISTS rentals ("
#         "rental_id INTEGER PRIMARY KEY AUTOINCREMENT,"
#         "customer_id INTEGER,"
#         "car_id INTEGER,"
#         "rental_date TEXT,"
#         "return_date TEXT,"
#         "days INTEGER,"
#         "total_amount REAL,"
#         "status TEXT DEFAULT 'Rented',"
#         "FOREIGN KEY(customer_id) REFERENCES customers(customer_id),"
#         "FOREIGN KEY(car_id) REFERENCES cars(car_id));");
# 
#     execute_sql(
#         "CREATE TABLE IF NOT EXISTS payments ("
#         "payment_id INTEGER PRIMARY KEY AUTOINCREMENT,"
#         "rental_id INTEGER,"
#         "amount REAL,"
#         "payment_date TEXT,"
#         "payment_status TEXT DEFAULT 'Paid',"
#         "FOREIGN KEY(rental_id) REFERENCES rentals(rental_id));");
# }
# 
# /* ---------- SAMPLE CARS ---------- */
# 
# void insert_sample_cars()
# {
#     execute_sql(
#         "INSERT OR IGNORE INTO cars "
#         "(car_number, brand, model, car_type, rent_per_day) VALUES "
#         "('TN01AB1234','Toyota','Innova','SUV',2500),"
#         "('TN02CD5678','Hyundai','Creta','SUV',2200),"
#         "('TN03EF9012','Maruti','Swift','Hatchback',1500),"
#         "('TN04GH3456','Honda','City','Sedan',2000),"
#         "('TN05IJ7890','Tata','Nexon','SUV',1800);");
# }
# 
# /* ---------- VIEW CARS ---------- */
# 
# void view_cars()
# {
#     sqlite3_stmt *stmt;
# 
#     const char *sql =
#         "SELECT car_id, car_number, brand, model, car_type, "
#         "rent_per_day, status FROM cars;";
# 
#     if (sqlite3_prepare_v2(db, sql, -1, &stmt, NULL) != SQLITE_OK)
#         return;
# 
#     printf("\n============================================================\n");
#     printf("                    CAR LIST\n");
#     printf("============================================================\n");
# 
#     printf("%-5s %-15s %-12s %-12s %-12s %-12s %-12s\n",
#            "ID", "Number", "Brand", "Model", "Type",
#            "Rent/Day", "Status");
# 
#     while (sqlite3_step(stmt) == SQLITE_ROW)
#     {
#         printf("%-5d %-15s %-12s %-12s %-12s ₹%-11.2f %-12s\n",
#                sqlite3_column_int(stmt, 0),
#                sqlite3_column_text(stmt, 1),
#                sqlite3_column_text(stmt, 2),
#                sqlite3_column_text(stmt, 3),
#                sqlite3_column_text(stmt, 4),
#                sqlite3_column_double(stmt, 5),
#                sqlite3_column_text(stmt, 6));
#     }
# 
#     sqlite3_finalize(stmt);
# }
# 
# /* ---------- REGISTER CUSTOMER ---------- */
# 
# void register_customer()
# {
#     char name[100], phone[30], email[100], address[150];
#     sqlite3_stmt *stmt;
# 
#     printf("\n========== CUSTOMER REGISTRATION ==========\n");
# 
#     printf("Enter Name    : ");
#     scanf(" %[^\n]", name);
# 
#     printf("Enter Phone   : ");
#     scanf(" %[^\n]", phone);
# 
#     printf("Enter Email   : ");
#     scanf(" %[^\n]", email);
# 
#     printf("Enter Address : ");
#     scanf(" %[^\n]", address);
# 
#     const char *sql =
#         "INSERT INTO customers(name, phone, email, address) "
#         "VALUES (?, ?, ?, ?);";
# 
#     sqlite3_prepare_v2(db, sql, -1, &stmt, NULL);
# 
#     sqlite3_bind_text(stmt, 1, name, -1, SQLITE_TRANSIENT);
#     sqlite3_bind_text(stmt, 2, phone, -1, SQLITE_TRANSIENT);
#     sqlite3_bind_text(stmt, 3, email, -1, SQLITE_TRANSIENT);
#     sqlite3_bind_text(stmt, 4, address, -1, SQLITE_TRANSIENT);
# 
#     if (sqlite3_step(stmt) == SQLITE_DONE)
#     {
#         printf("\nCustomer registered successfully!\n");
#         printf("Customer ID: %lld\n",
#                sqlite3_last_insert_rowid(db));
#     }
#     else
#     {
#         printf("\nCustomer registration failed.\n");
#     }
# 
#     sqlite3_finalize(stmt);
# }
# 
# /* ---------- VIEW CUSTOMERS ---------- */
# 
# void view_customers()
# {
#     sqlite3_stmt *stmt;
# 
#     const char *sql =
#         "SELECT customer_id, name, phone, email, address "
#         "FROM customers;";
# 
#     sqlite3_prepare_v2(db, sql, -1, &stmt, NULL);
# 
#     printf("\n============================================================\n");
#     printf("                  CUSTOMER LIST\n");
#     printf("============================================================\n");
# 
#     printf("%-5s %-20s %-15s %-25s %-15s\n",
#            "ID", "Name", "Phone", "Email", "Address");
# 
#     while (sqlite3_step(stmt) == SQLITE_ROW)
#     {
#         printf("%-5d %-20s %-15s %-25s %-15s\n",
#                sqlite3_column_int(stmt, 0),
#                sqlite3_column_text(stmt, 1),
#                sqlite3_column_text(stmt, 2),
#                sqlite3_column_text(stmt, 3),
#                sqlite3_column_text(stmt, 4));
#     }
# 
#     sqlite3_finalize(stmt);
# }
# 
# /* ---------- RENT CAR ---------- */
# 
# void rent_car()
# {
#     int customer_id, car_id, days;
#     double rent_per_day, total;
#     sqlite3_stmt *stmt;
# 
#     printf("\n========== RENT CAR ==========\n");
# 
#     printf("Enter Customer ID : ");
#     scanf("%d", &customer_id);
# 
#     printf("Enter Car ID      : ");
#     scanf("%d", &car_id);
# 
#     printf("Enter Number of Days : ");
#     scanf("%d", &days);
# 
#     if (days <= 0)
#     {
#         printf("Invalid number of days.\n");
#         return;
#     }
# 
#     const char *check_sql =
#         "SELECT rent_per_day FROM cars "
#         "WHERE car_id = ? AND status = 'Available';";
# 
#     sqlite3_prepare_v2(db, check_sql, -1, &stmt, NULL);
#     sqlite3_bind_int(stmt, 1, car_id);
# 
#     if (sqlite3_step(stmt) != SQLITE_ROW)
#     {
#         printf("\nCar not available or invalid Car ID.\n");
#         sqlite3_finalize(stmt);
#         return;
#     }
# 
#     rent_per_day = sqlite3_column_double(stmt, 0);
#     sqlite3_finalize(stmt);
# 
#     total = rent_per_day * days;
# 
#     const char *insert_sql =
#         "INSERT INTO rentals "
#         "(customer_id, car_id, rental_date, days, total_amount, status) "
#         "VALUES (?, ?, date('now'), ?, ?, 'Rented');";
# 
#     sqlite3_prepare_v2(db, insert_sql, -1, &stmt, NULL);
# 
#     sqlite3_bind_int(stmt, 1, customer_id);
#     sqlite3_bind_int(stmt, 2, car_id);
#     sqlite3_bind_int(stmt, 3, days);
#     sqlite3_bind_double(stmt, 4, total);
# 
#     if (sqlite3_step(stmt) == SQLITE_DONE)
#     {
#         long long rental_id = sqlite3_last_insert_rowid(db);
# 
#         printf("\n====================================\n");
#         printf("          CAR RENTED\n");
#         printf("====================================\n");
#         printf("Rental ID   : %lld\n", rental_id);
#         printf("Total Amount: ₹%.2f\n", total);
#         printf("Status      : Rented\n");
#         printf("====================================\n");
# 
#         char update_sql[200];
# 
#         snprintf(update_sql, sizeof(update_sql),
#                  "UPDATE cars SET status='Rented' "
#                  "WHERE car_id=%d;", car_id);
# 
#         execute_sql(update_sql);
#     }
#     else
#     {
#         printf("\nRental failed.\n");
#     }
# 
#     sqlite3_finalize(stmt);
# }
# 
# /* ---------- RETURN CAR ---------- */
# 
# void return_car()
# {
#     int rental_id;
#     sqlite3_stmt *stmt;
# 
#     printf("\n========== RETURN CAR ==========\n");
# 
#     printf("Enter Rental ID : ");
#     scanf("%d", &rental_id);
# 
#     const char *sql =
#         "SELECT car_id, total_amount "
#         "FROM rentals "
#         "WHERE rental_id = ? AND status = 'Rented';";
# 
#     sqlite3_prepare_v2(db, sql, -1, &stmt, NULL);
#     sqlite3_bind_int(stmt, 1, rental_id);
# 
#     if (sqlite3_step(stmt) != SQLITE_ROW)
#     {
#         printf("\nRental not found or already returned.\n");
#         sqlite3_finalize(stmt);
#         return;
#     }
# 
#     int car_id = sqlite3_column_int(stmt, 0);
#     double amount = sqlite3_column_double(stmt, 1);
# 
#     sqlite3_finalize(stmt);
# 
#     char update_rental[300];
# 
#     snprintf(update_rental, sizeof(update_rental),
#              "UPDATE rentals SET "
#              "return_date=date('now'), status='Returned' "
#              "WHERE rental_id=%d;",
#              rental_id);
# 
#     execute_sql(update_rental);
# 
#     char update_car[200];
# 
#     snprintf(update_car, sizeof(update_car),
#              "UPDATE cars SET status='Available' "
#              "WHERE car_id=%d;",
#              car_id);
# 
#     execute_sql(update_car);
# 
#     sqlite3_stmt *payment_stmt;
# 
#     const char *payment_sql =
#         "INSERT INTO payments "
#         "(rental_id, amount, payment_date, payment_status) "
#         "VALUES (?, ?, date('now'), 'Paid');";
# 
#     sqlite3_prepare_v2(db, payment_sql, -1, &payment_stmt, NULL);
# 
#     sqlite3_bind_int(payment_stmt, 1, rental_id);
#     sqlite3_bind_double(payment_stmt, 2, amount);
# 
#     sqlite3_step(payment_stmt);
# 
#     sqlite3_finalize(payment_stmt);
# 
#     printf("\n====================================\n");
#     printf("          CAR RETURNED\n");
#     printf("====================================\n");
#     printf("Rental ID    : %d\n", rental_id);
#     printf("Total Amount : ₹%.2f\n", amount);
#     printf("Payment      : Paid\n");
#     printf("Return Date  : Today\n");
#     printf("====================================\n");
# }
# 
# /* ---------- RENTAL HISTORY ---------- */
# 
# void rental_history()
# {
#     sqlite3_stmt *stmt;
# 
#     const char *sql =
#         "SELECT r.rental_id, c.name, "
#         "ca.brand, ca.model, "
#         "r.rental_date, r.return_date, "
#         "r.days, r.total_amount, r.status "
#         "FROM rentals r "
#         "JOIN customers c ON r.customer_id=c.customer_id "
#         "JOIN cars ca ON r.car_id=ca.car_id;";
# 
#     sqlite3_prepare_v2(db, sql, -1, &stmt, NULL);
# 
#     printf("\n============================================================\n");
#     printf("                    RENTAL HISTORY\n");
#     printf("============================================================\n");
# 
#     while (sqlite3_step(stmt) == SQLITE_ROW)
#     {
#         printf("\nRental ID   : %d",
#                sqlite3_column_int(stmt, 0));
# 
#         printf("\nCustomer    : %s",
#                sqlite3_column_text(stmt, 1));
# 
#         printf("\nCar         : %s %s",
#                sqlite3_column_text(stmt, 2),
#                sqlite3_column_text(stmt, 3));
# 
#         printf("\nRental Date : %s",
#                sqlite3_column_text(stmt, 4));
# 
#         printf("\nReturn Date : %s",
#                sqlite3_column_text(stmt, 5)
#                    ? (const char *)sqlite3_column_text(stmt, 5)
#                    : "Not Returned");
# 
#         printf("\nDays        : %d",
#                sqlite3_column_int(stmt, 6));
# 
#         printf("\nTotal       : ₹%.2f",
#                sqlite3_column_double(stmt, 7));
# 
#         printf("\nStatus      : %s\n",
#                sqlite3_column_text(stmt, 8));
# 
#         printf("--------------------------------------------\n");
#     }
# 
#     sqlite3_finalize(stmt);
# }
# 
# /* ---------- REVENUE REPORT ---------- */
# 
# void revenue_report()
# {
#     sqlite3_stmt *stmt;
# 
#     const char *sql =
#         "SELECT "
#         "COUNT(*), "
#         "COALESCE(SUM(amount),0) "
#         "FROM payments "
#         "WHERE payment_status='Paid';";
# 
#     sqlite3_prepare_v2(db, sql, -1, &stmt, NULL);
# 
#     if (sqlite3_step(stmt) == SQLITE_ROW)
#     {
#         int payments = sqlite3_column_int(stmt, 0);
#         double revenue = sqlite3_column_double(stmt, 1);
# 
#         printf("\n====================================\n");
#         printf("          REVENUE REPORT\n");
#         printf("====================================\n");
#         printf("Total Payments : %d\n", payments);
#         printf("Total Revenue  : ₹%.2f\n", revenue);
#         printf("====================================\n");
#     }
# 
#     sqlite3_finalize(stmt);
# }
# 
# /* ---------- CUSTOMER MENU ---------- */
# 
# void customer_menu()
# {
#     int choice;
# 
#     do
#     {
#         printf("\n============================================\n");
#         printf("              CUSTOMER MENU\n");
#         printf("============================================\n");
#         printf("1. Register Customer\n");
#         printf("2. View Cars\n");
#         printf("3. Rent Car\n");
#         printf("4. Return Car\n");
#         printf("5. Rental History\n");
#         printf("6. Back\n");
#         printf("============================================\n");
# 
#         printf("Enter Choice: ");
#         scanf("%d", &choice);
# 
#         switch (choice)
#         {
#             case 1:
#                 register_customer();
#                 break;
# 
#             case 2:
#                 view_cars();
#                 break;
# 
#             case 3:
#                 rent_car();
#                 break;
# 
#             case 4:
#                 return_car();
#                 break;
# 
#             case 5:
#                 rental_history();
#                 break;
# 
#             case 6:
#                 break;
# 
#             default:
#                 printf("Invalid choice.\n");
#         }
# 
#     } while (choice != 6);
# }
# 
# /* ---------- ADMIN MENU ---------- */
# 
# void admin_menu()
# {
#     int choice;
# 
#     do
#     {
#         printf("\n============================================\n");
#         printf("                ADMIN MENU\n");
#         printf("============================================\n");
#         printf("1. View Customers\n");
#         printf("2. View Cars\n");
#         printf("3. Rental History\n");
#         printf("4. Revenue Report\n");
#         printf("5. Back\n");
#         printf("============================================\n");
# 
#         printf("Enter Choice: ");
#         scanf("%d", &choice);
# 
#         switch (choice)
#         {
#             case 1:
#                 view_customers();
#                 break;
# 
#             case 2:
#                 view_cars();
#                 break;
# 
#             case 3:
#                 rental_history();
#                 break;
# 
#             case 4:
#                 revenue_report();
#                 break;
# 
#             case 5:
#                 break;
# 
#             default:
#                 printf("Invalid choice.\n");
#         }
# 
#     } while (choice != 5);
# }
# 
# /* ---------- MAIN ---------- */
# 
# int main()
# {
#     if (sqlite3_open("car_rental_system.db", &db) != SQLITE_OK)
#     {
#         printf("Database connection failed.\n");
#         return 1;
#     }
# 
#     execute_sql("PRAGMA foreign_keys = ON;");
# 
#     create_tables();
#     insert_sample_cars();
# 
#     int choice;
# 
#     printf("\n");
#     printf("============================================================\n");
#     printf("              CAR RENTAL MANAGEMENT SYSTEM\n");
#     printf("============================================================\n");
# 
#     do
#     {
#         printf("\n==================== MAIN MENU ====================\n");
#         printf("1. Customer\n");
#         printf("2. Admin\n");
#         printf("3. Exit\n");
#         printf("====================================================\n");
# 
#         printf("Enter Choice: ");
#         scanf("%d", &choice);
# 
#         switch (choice)
#         {
#             case 1:
#                 customer_menu();
#                 break;
# 
#             case 2:
#                 admin_menu();
#                 break;
# 
#             case 3:
#                 printf("\nThank you for using Car Rental System!\n");
#                 break;
# 
#             default:
#                 printf("\nInvalid choice.\n");
#         }
# 
#     } while (choice != 3);
# 
#     sqlite3_close(db);
# 
#     return 0;
# }

!gcc car_rental.c -o car_rental -lsqlite3

!./car_rental

from google.colab import files
files.download("car_rental.c")

from google.colab import files
files.download("car_rental.c")